<?php $this->load->view('common/header'); ?>
<section class="content_section bg-gray head_text">
    <div class="content-wrap">

        <div class="container clearfix container2">
            <div class="privacy-policy">
                <div class="text-center fancy-title">
                    <h1 class="pl6 pl0-xs bold_heading">
                        Terms & Conditions
                    </h1>

                </div>
                <div class="row">
                    <div class="col-md-12">

                        <div class="t_and_c">
                            <p><strong>This Service Agreement, hereinafter referred to as the &ldquo;Agreement&rdquo; or &ldquo;service contract&rdquo;, is issued by the entity listed for your state on the Coverage Summary page.  Such entity is hereinafter referred to as &ldquo;RHW&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, and/or &ldquo;our&rdquo;, or &ldquo;provider&rdquo;.  The owner of the property covered by this Agreement is hereinafter referred to as &ldquo;you&rdquo; and/or &ldquo;your&rdquo;, or &ldquo;contract holder&rdquo;.  RHW offers home service contracts, which are not warranties.  Terms may vary in different states. RHW reserves the right to revise this Agreement at any time and you are deemed to be apprised of and bound by any changes to this Agreement.</strong></p>
                            <p>Certain items and events are not covered by this Agreement.  Please read the Agreement carefully.  Coverage includes only certain mechanical failures of the specific items listed as covered on your Agreement Coverage Summary and excludes all other failures and/or items.  The Agreement Coverage Summary is attached to and made a part of this Agreement. </p>
                            <p><strong>I.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; BASIS FOR COVERAGE</strong></p>
                            <p>During the term of this Agreement, we agree to pay the covered costs to repair or replace the items listed as covered on your Agreement Coverage Summary if any such items become inoperable due to mechanical failure caused by normal wear and tear.&nbsp; Determination of Coverage including the operational condition as of the Agreement effective date for any claim will be made solely by us, considering but not limited to, our independent contractor&rsquo;s diagnosis, hereinafter referred to as the &ldquo;Service Contractor&rdquo;.&nbsp; This Agreement does not cover any known or unknown pre-existing conditions.&nbsp; It is understood that WE ARE NOT A SERVICE CONTRACTOR and is not itself undertaking to repair or replace any such systems or components. This Agreement covers single-family homes, new construction homes, condominiums, townhomes, and mobile homes under 5,000 square feet, unless an alternative dwelling type (i.e. above 5,000 square feet or multi-unit home) is applied, and appropriate fees are paid.&nbsp; This Agreement will not cover systems or appliances within (a) commercial properties; (b) residential properties used for business purposes, including, but not limited to, dwellings used for rest homes, day care centers, schools and/or professional offices; (c) common areas of condominiums, multi-family houses and/or cooperatives; (d) vacant properties, and; (e) foreclosed/short sold properties. Coverage applies to the systems and components mentioned as &ldquo;covered&rdquo; in accordance with the terms and conditions of this Agreement so long as such systems and components:</p>
                            <p>A.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Become inoperable due to normal wear and tear; and</p>
                            <p>B.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Are in place and in proper working order on the effective date of this Agreement; and </p>
                            <p>C.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Are located inside the confines of the main foundation of the home or attached or detached garage, with the exception of the air conditioner, exterior pool/spa, septic system, and well pump.</p>
                            <p><strong>II.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; TERM</strong></p>
                            <p>Coverage starts 30 days after acceptance of application by us and receipt of applicable Agreement fees and continues for 365 days from that date.&nbsp; We reserve the right to waive the 30-day grace period so long as you provide proof or prior coverage, showing no lapse of coverage, from another home service provider.&nbsp; Waiving of the 30-day waiting period is at the sole discretion of us. &nbsp; &nbsp;&nbsp;</p>
                            <p><strong>III.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; REQUESTING SERVICE &ndash; CALL (888)400-3096</strong></p>
                            <p>A.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We must be notified as soon as the malfunction is discovered and prior to expiration of the Agreement.&nbsp; You can request service by calling 1-860-777-0204.&nbsp; We will accept service requests 24 hours a day, 7 days a week.&nbsp; We will not provide service until all past due Trade Service Call Fees and Plan Fees are made current.&nbsp; </p>
                            <p>B.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Upon request for service under normal circumstances, we will contact an authorized Service Contractor within two (2) days during normal business hours and four (4) days on weekends and holidays after you request service. The authorized Service Contractor will contact you to schedule a mutually convenient appointment during normal business hours. We will determine what repairs constitute an emergency and will make reasonable efforts to expedite emergency service.&nbsp; We will accept your request to expedite scheduling of non-emergency service only when a Service Contractor is available.&nbsp; If the Service Contractor agrees to expedite scheduling of a non-emergency service request, you may be required to pay an additional fee.</p>
                            <p>C.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We have the sole and absolute right to select the Service Contractor to perform the service.&nbsp; We will not reimburse for services performed without its prior approval.</p>
                            <p>D.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We reserve the right to obtain a second opinion at our expense.&nbsp; In the event that we inform you the malfunction is not covered under this Agreement, you have the right to request a second opinion of the cause of the malfunction.&nbsp; You must ask us for a second opinion from another Service Contractor within seven (7) days from us informing you the malfunction is not covered.&nbsp; In the event that the outcome of the second opinion is different than the first opinion, then we may, in our discretion, decide whether to accept Coverage under this Agreement. If you request a second opinion, you will be responsible for the payment of an additional Trade Service Call Fee only if the outcome of the second opinion is the same as the initial opinion.</p>
                            <p>E.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In the event we authorize or request you to contact an independent service contractor to perform a covered service, we will provide reimbursement for an authorized amount of the cost you incur for the repair or replacement services.&nbsp; Acceptable proof of the repair and your actual itemized costs must be provided to and approved by us before any reimbursement will be paid.&nbsp; We are not responsible for expenses you incur without our express consent.&nbsp; We will not reimburse you for any costs associated with unauthorized repairs or work performed by unauthorized contractors.</p>
                            <p>F.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If service work performed under this contract should fail, then we will make the necessary repairs without an additional Trade Service Call Fee for a period of 90 days on parts and 30 days on labor.</p>
                            <p><strong>IV.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; TRADE SERVICE CALL FEE</strong></p>
                            <p>NOTE: The amount of your Trade Service Call Fee is listed on your Agreement Coverage Summary.</p>
                            <p>A.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; You are required to pay a Trade Service Call Fee for each trade service request you submit to us.</p>
                            <p>B.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The Trade Service Call Fee applies to each call dispatched and scheduled, including but not limited to those calls where Coverage is approved or denied, included or excluded, covered or not covered.&nbsp; The Trade Service Call Fee also applies in the event you fail to be present at a scheduled time, or in the event you cancel a service request at the time a Service Contractor is in route to your home or at your home.&nbsp; Failure to pay the Trade Service Call Fee will result in suspension or cancellation of Agreement until such time as the proper Trade Service Call Fee is paid.&nbsp; At that time, the Agreement may be reinstated; however, the contract period will not be extended.</p>
                            <p>C.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If a particular repair or replacement fails within 30 days, we will send a Service Contractor to repair the failure and you will not be charged an additional Trade Service Call Fee.</p>
                            <p><strong>V.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; COVERAGE</strong></p>
                            <p>Coverage is dependent on plan you selected. Please refer to your Agreement Coverage Summary page.&nbsp; Coverage is for no more than one (1) unit, system, or appliance, unless additional fees are paid or specified otherwise.&nbsp; If no additional fees are paid, covered unit, system, or appliance is at our sole discretion.&nbsp; Certain limitations of liability apply to covered systems and appliances.</p>
                            <p>A.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Air Conditioning System</p>
                            <p>Note: Coverage available on Air Conditioning units up to a 5-ton capacity, and for residential use only.</p>
                            <p>COVERED: Mechanical parts and components of two (2) ducted electric central air conditioning systems.  All components and parts for units below 13 SEER and/or R-22 equipment, and when we are unable to facilitate repair and/or replacement of failed covered equipment at the current SEER rating or with R-22 equipment, repair and/or replacement will be performed with 13 SEER/R410A equipment and/or 7.7 HSPF or higher compliant, except:</p>
                            <p>NOT COVERED: Filters; filter driers; condenser casings; registers and grills; water towers; humidifiers; chillers; electronic air cleaners; window units; non-ducted wall units; mini-split wall units; gas air conditioning systems; water evaporative coolers; swamp coolers; condensate pumps; thermal expansion valves; all exterior condensing, cooling and pump pads; disconnect boxes; roof mounts, jacks, stands or supports; cost for crane rentals; electronic, computerized, and manual systems management and zone controllers; commercial grade equipment; refrigerant conversion; leak detections; water leaks; drain line stoppages or drain pans; failures due to open windings, line restrictions, filter driers; maintenance; rusted and/or corroded coils; component short to ground; noise without a related mechanical failure; improperly sized units; air conditioning with mismatched condensing unit and evaporative coil per manufacturer specifications; improper use of metering devices (i.e. thermal expansion valves).  We are not responsible for the costs associated with matching dimensions, brand or color made.  We will not pay for any modifications or upgrades necessitated by the repair of existing equipment or the installation of new equipment. We will pay up to $10 per pound per occurrence for refrigerant. You are responsible for payment of any costs in excess of $10 per pound.</p>
                            <p>B.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Heating System</p>
                            <p>Note: Coverage available on units up to a 5-ton capacity, and for residential use only.</p>
                            <p>COVERED: Mechanical parts and components of two (2) systems, either hot water and steam heating system or centrally ducted forced air gas/electric/oil heating system or electric baseboard units, if providing the primary source of heat in dwelling, as follows: accessible ductwork from covered heating unit to point of attachment to register/grill; blower fan motors; burners; controls; fan blades; heat/cool thermostats (programmable and electronic set back units will be replaced only with standard units); heating elements; ignitor and pilot assemblies; internal system controls; wiring; and relays; motors (excludes dampers); and switches. Electric baseboard units are covered if they are the primary source of heating for the property.</p>
                            <p>NOT COVERED: Chimneys, flues, and liners; cleaning and re-lighting of pilots; concrete encased or inaccessible ductwork; concrete encased or inaccessible steam or radiant heating coils or lines; conditions of water flow restriction due to scale, rust, minerals and other deposits; heat exchangers; cracked heat exchangers; rusted and/or corroded heat exchangers; maintenance and cleaning; calcium build-up; evaporator coil pan; primary or secondary drain pans; fossil and dual fuel control systems and other energy management systems and controls; dampers; asbestos insulated ductwork or piping; electric baseboard heat unless primary heating system in home; filters (including electronic/electrostatic and de-ionizing filter systems); fireplaces and their respective components and gas lines; free-standing or portable heating units; heat lamps; pellet stoves; fuel storage tanks, lines, and filters; gas log systems, including gas feed lines; valves; key valves; oil filters, nozzles, or strainers; humidifiers; inaccessible water/steam lines leading to or from system; backflow preventers; individual space heaters; panels and/or cabinetry; radiant heating systems built into walls, floors or ceilings; registers and grills; secondary units; solar heating devices and components; maintenance; noise without a related mechanical failure; improperly sized heating systems; mismatched systems; and structural components.</p>
                            <p>C.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Refrigerator</p>
                            <p>Note: Refrigerator must be located in the kitchen.</p>
                            <p>COVERED: All components and parts, including integral freezer unit, except: </p>
                            <p>NOT COVERED: Racks; shelves; glass; lighting; handles; doors, door seals, hinges, and gaskets; Freon; disposal and recapture of Freon; ice makers, ice crushers, beverage dispensers and their respective equipment; water lines and valve to ice maker; line restrictions; leaks of any kind; maintenance; interior thermal shells; freezers which are not an integral part of the refrigerator; wine chillers or mini refrigerators; food spoilage; noise without a related mechanical failure; multi-media centers and internet connection components.</p>
                            <p>D.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Clothes Washer</p>
                            <p>COVERED: All components and parts, except: </p>
                            <p>NOT COVERED: Soap dispensers; removable minitubs; filter screens; knobs and dials; doors, door seals and hinges; glass; leveling and balancing; damage to clothing; commercial units; noise without a related mechanical failure; conditions of water flow restriction due to scale, rust, minerals and other deposits.</p>
                            <p>E.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Clothes Dryer</p>
                            <p>COVERED: All components and parts, except:</p>
                            <p>NOT COVERED: Venting; lint screens; knobs and dials; doors, door seals, and hinges; glass; leveling and balancing; noise without a related mechanical failure; damage to clothing; conditions of air flow restriction due to a lack of maintenance and/or clogged lint screens.&nbsp; </p>
                            <p>F.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Plumbing System and Stoppage</p>
                            <p>Note: Mainline stoppages are only covered if there is an accessible ground level clean out. </p>
                            <p>COVERED: Leaks and breaks of water, drain, gas, waste or vent lines, except if caused by freezing or roots; toilet tanks, bowls and mechanisms within the toilet tank (replaced with builder&rsquo;s grade as necessary); toilet wax ring seals; built-in bathtub whirlpool motor and pump assemblies; stoppages and/or clogs in drain and sewer lines up to 100 feet from access point. Repair and finish of any walls or ceilings where it is necessary to break through to effect repair is only covered to the following extent: repair of walls or ceilings to rough finish up to $500 per claim. Rough finish is defined to include hanging of drywall, patching of drywall, stucco, and lath. Repair to rough finish does not include supplies or labor for paint, sanding, wall texture, wallpaper and/or tile work.</p>
                            <p>NOT COVERED: All plumbing in or under the ground, foundation or slab; all piping and plumbing outside of the perimeter of the foundation; any piping or plumbing in a detached structure; stoppage of concrete encased lines; any fees for locating, accessing or installing cleanouts; removal of water closets/toilets in order to clear stoppages, any fees for photo/video equipment, hydro-jetting equipment; jet or steam clearing; chemicals; stoppages caused by root invasion; stoppages caused by foreign objects, such as but not limited to, sanitary wipes, toys, bottle caps, etc.; bath tubs; toilet lids and seats; sinks; cracked porcelain; basket and strainers; pop-up assemblies; tub waste overflow; glass; bidets; electronic toilets/bidets; caulking or grout; color or purity of the water in the system; concrete encased plumbing; conditions of insufficient or excessive water pressure; conditions of water flow restriction due to scale, rust, sediment, and other deposits; failures due to calcium build-up; hose bibs; faucets and fixtures; faucet and fixtures cartridges; valves for shower, tub, and diverter angle stops, rinses and gate valves; water softeners; freeze damage; holding and pressure tanks; jet pumps; laundry tubs; lawn sprinkler systems; saunas and/or steam systems; polybutylene or quest piping; galvanized drain lines; drum traps; flange; repair and finish of any floors where it is necessary to break through to effect repairs; septic tanks and systems in or outside of the home; sewage ejector pumps; sewer and water laterals; shower enclosures and base pans. We will pay no more than $500 per contract term for access, diagnosis, repair and/or replacement. </p>
                            <p>G.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Water Heater</p>
                            <p>COVERED: All components and parts for gas and/or electric hot water heaters, including circulating pumps, except:</p>
                            <p>NOT COVERED: Auxiliary and secondary holding/storage tanks; main, holding or storage tanks; expansion tanks; base pans; drain pans and drain lines; line restrictions; pressure reducing valve; sediment build-up; mineral and/or calcium build-up; rust and corrosion; combustion shutdown; color or purity of water; flues; vent pipes/lines; insulation and insulation blankets; heat recovery units; tankless hot water heaters; low boy and/or squat water heaters; solar water heaters including all solar components and parts; any noise without a related mechanical failure; racks; straps; timers; energy management systems; commercial grade equipment and units exceeding 75 gallons.&nbsp;<span class="tc2">We will pay no more than $500 per contract term for access, diagnosis, repair and/or replacement.</span>&nbsp;</p>
                            <p>H.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Whirlpool Bathtub</p>
                            <p>COVERED: Mechanical parts and components including accessible electrical controls; accessible plumbing lines; air pumps; gaskets; and primary circulation pump and motor.</p>
                            <p>NOT COVERED: Bathtub shell; heaters; lights; multi-media systems; faucets and fixtures; caulking and grout; drains; jets; conditions of water flow restriction due to scale, rust, minerals and other deposits; failures due to dry operation of equipment; gaining access to electrical, component parts, and/or piping; tiles and marble; and tub enclosure. We will pay no more than $500 per contract term for access, diagnosis, repair and/or replacement.</p>
                            <p>I.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Electrical System </p>
                            <p>COVERED: All components and parts, except:</p>
                            <p>NOT COVERED: Attic exhaust fans; direct current (DC) wiring and systems; exterior wiring and components (except main panels mounted to exterior wall); any wiring or components servicing a detached structure; fire, carbon monoxide alarm and/or detection systems; batteries; intercom or speaker systems; doorbells; multi-media systems; lighting fixtures; load control devices; low voltage systems including wiring and relays; service entrance cables; telephone systems; telephone wiring; cable wiring; alarm and/or security systems and wiring; timers; touch pad assemblies; transmitters and remotes; utility meter base pans; solar power systems and panels; all solar components and parts; energy management systems; commercial grade equipment; auxiliary or sub-panels; bus bars; broken and/or severed wires; rerunning of new wiring for broken wires; wire tracing; central vacuum systems. Failures and conditions caused by inadequate wiring capacity, inadequate size breakers, circuit overload, power failure/shortage or surge, and corrosion are not covered. We will pay no more than $500 per contract term for access, diagnosis, repair and/or replacement.</p>
                            <p>J.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Oven/Range/Stove/Cooktop</p>
                            <p>COVERED: All mechanical components and parts, except:</p>
                            <p>NOT COVERED: Doors; door seals; hinges; handles; glass; knobs; lighting; clocks (unless they affect the cooking function of the unit); meat probe assemblies, rotisseries; racks and trays; downdrafts; range exhaust hoods; independent telescoping range exhaust; exhaust fan not solely for venting range/cooktop fumes; filters and screens; venting; sensi-heat burners will only be replaced with standard burners; drip pans; self-cleaning mechanisms including door latches; commercial units.</p>
                            <p>K.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Built-In Microwave</p>
                            <p>COVERED: All mechanical components and parts, except:</p>
                            <p>NOT COVERED: Doors; hinges; handles; glass; knobs; lights; clocks (unless they affect the cooking function of the unit); meat probe assemblies, rotisseries; racks and trays; interior linings; arcing; portable or counter top units.</p>
                            <p>L.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dishwasher</p>
                            <p>COVERED: All mechanical components and parts, except:</p>
                            <p>NOT COVERED: Doors; door seals; hinges; handles; glass; knobs; racks, trays, and baskets; rollers; damage caused by broken glass; noise without a related mechanical failure; maintenance and cleaning; commercial units; portable units.</p>
                            <p>M.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Garbage Disposal</p>
                            <p>COVERED: All components and parts, including entire unit, except:</p>
                            <p>NOT COVERED: Failures and/or jams caused by bones, eggshells; glass, or foreign objects other than food.</p>
                            <p>N.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Trash Compactor </p>
                            <p>COVERED: All components and parts, except:</p>
                            <p>NOT COVERED: Portable units; lock and key assemblies; removable buckets; doors; door seals; hinges; handles; damage caused by overloading; commercial units.</p>
                            <p>O.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ductwork</p>
                            <p>COVERED: Duct from heating and air conditioning unit to point of attachment at registers or grills, except:</p>
                            <p>NOT COVERED: Registers and grills; insulation; insulated ductwork; asbestos; vents, flues and breaching; ductwork exposed to outside elements; improperly sized ductwork; separation due to settlement and/or lack of support; damper motors; diagnostic testing of, or locating leaks to ductwork, including but not limited to, as required by any federal, state or local law, ordinance or regulation, or when required due to the installation or replacement of system equipment. We will provide access to ductwork through unobstructed walls, ceilings or floors, only, and will return the access opening to rough finish condition. With respect to concrete covered, embedded, encased, or otherwise inaccessible ductwork, we will pay no more than $500 per contract term for access, diagnosis, repair and/or replacement. Rough finish is defined to include hanging of drywall, patching of drywall, stucco, and lath. Repair to rough finish does not include supplies or labor for paint, sanding, wall texture, wallpaper and/or tile work. We shall not be responsible for payment of the cost to remove and replace any built-in appliances, cabinets, floor coverings or other obstructions impeding access to walls, ceilings, and/or floors.</p>
                            <p>P.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Garage Door Opener</p>
                            <p>Note: Coverage is for no more than one (1) unit, system, or appliance, unless additional fees are paid. </p>
                            <p>COVERED: All components and parts, except:</p>
                            <p>NOT COVERED: Garage doors; hinges; springs; sensors; chains; travelers; door track assemblies; rollers; lights; keypads; wall buttons; remote receiving and/or transmitting devices.</p>
                            <p>Q.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ceiling and Exhaust Fans</p>
                            <p>Note: Coverage is for no more than two (2) units, systems, or appliances, unless additional fees are paid. Builder's standard equipment is used when replacement is necessary.</p>
                            <p>COVERED: Motors; switches; controls; bearings, except:</p>
                            <p>NOT COVERED: Kitchen exhaust fans; range exhaust fans; fan blades; belts; shutters; filters; lighting. We will pay no more than $400 per contract term for access, diagnosis, repair and/or replacement.&nbsp;</p>
                            <p><strong>VI.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; OPTIONAL COVERAGE</strong></p>
                            <p>Optional Coverage requires additional payment per item, system, or appliance.&nbsp; You may purchase any Optional Coverage for up to 30 days after commencement of Coverage. However, Coverage shall not commence until receipt of payment by us and such Coverage shall expire upon expiration of Coverage period in section II.</p>
                            <p>A.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Pool/Spa Equipment</p>
                            <p>Note: Shared equipment is covered. If equipment is not shared, then only one or the other is covered unless an additional fee is paid.</p>
                            <p>COVERED: Above ground components and parts of the pumping, and filtration system including pool sweep motor and pump; pump motor; blower motor and timer; filter; filter timer; gaskets; timer; valves, limited to back flush, actuator, check, and 2 and 3-way valves; relays and switches; above ground plumbing pipes and wiring, except:</p>
                            <p>NOT COVERED: Portable or above ground spas; access to pool and spa equipment; lights; liners and tile; jets; ornamental fountains, waterfalls and their pumping systems; auxiliary pumps; pool cover and related equipment; fill line and fill valves; built-in or detachable cleaning equipment including, without limitation, pool sweeps, pop-up heads, turbo valves, skimmers, chlorinators, and ionizers; fuel storage tanks; disposable filtration mediums; heat pump; heaters; control panels; control boards; multi-media centers; dehumidifiers; salt water generators and components; salt water systems; cracked or corroded filter casings; grids; cartridges; maintenance; structural defects; solar equipment and components. We will pay no more than $500 per contract term for access, diagnosis, repair and/or replacement.</p>
                            <p>B.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Limited Roof Leak</p>
                            <p>Note: Coverage applies to single family homes only.</p>
                            <p>COVERED: Repair of shake and composition roof leaks over the occupied living area.</p>
                            <p>NOT COVERED: Leaks related to patios; porches; decks; metal roofs; foam roofs; shingles; cemwood shakes; cracked and/or missing material; tiles; tar and gravel; flat or built-up roofs; structural leaks; asphalt; gutters; downspouts; skylights; flashing; patio covers; solar components; attic vents; roof jacks; satellite components; antennae; chimney components; partial roof replacement; preventative maintenance. We will pay no more than $500 per contract term for access, diagnosis, repair and/or replacement.</p>
                            <p>C.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Central Vacuum</p>
                            <p>COVERED: All mechanical components and parts, except:</p>
                            <p>NOT COVERED: Ductwork; piping; nozzles; hoses; blockages; accessories.</p>
                            <p>D.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sump Pump</p>
                            <p>COVERED: Mechanical parts and components of permanently installed sump pump for ground water, within the foundation of the home or attached garage, except:</p>
                            <p>NOT COVERED: Any unit located outside the covered property and/or within crawl spaces; back-up power assemblies; portable or non-hard piped installed units; sewerage ejector pumps; backflow preventers; check valves; piping modifications for new installs. We will pay no more than $500 per contract term for access, diagnosis, repair and/or replacement.</p>
                            <p>E.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Well Pump</p>
                            <p>COVERED: All components and parts of well pump utilized as a main source of water to the home, except: </p>
                            <p>NOT COVERED: Above or underground piping, cable or electrical lines leading to or from the well pump, including those that are located within the well casing; holding or storage tanks; digging; locating pump; pump retrieval; redrilling of wells; well casings; pressure tanks; pressure switches and gauges; check valve; relief valve; drop pipe; piping or electrical lines leading to or connecting pressure tank and main dwelling including wiring from control box to the pump; booster pumps; well pump and all well pump components for geothermal and/or water source heat pumps. We will pay no more than $500 per contract term for access, diagnosis, repair and/or replacement.</p>
                            <p>F.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Septic System</p>
                            <p>COVERED: Sewage ejector pump for septic system only; jet pump; aerobic pump. Clearing of stoppages within the connecting waste line (leading from the house to the primary septic tank) which are attributable to normal wear and tear and can be accessed through an existing clean out without excavation.</p>
                            <p>NOT COVERED: Broken or collapsed sewer lines; tile fields; leach beds; leach lines; lateral lines; tanks; insufficient capacity; seepage pits; cesspools and sewage ejector pumps not associated with the septic system. We do not cover the cost associated with locating or gaining access to the septic tank or sewer hook-ups nor do we cover the cost of installing cleanouts or hook ups if they do not already exist; disposal of waste; pumping; chemical treatments of the septic tank or sewer lines, stoppages caused by root invasion and/or stoppages caused by foreign objects, such as but not limited to, toys and bottle caps. We will pay no more than $500 per contract term for access, diagnosis, repair and/or replacement.</p>
                            <p>G.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Septic Tank Pumping</p>
                            <p>COVERED: The septic tank will be pumped once during the Agreement term if the stoppage is due to septic back up only. Coverage applies to main line stoppages and/or clogs and must have existing access or clean out. Coverage can only become effective if a septic certification was completed within 90 days prior to close of sale. We reserve the right to request a copy of the certification prior to service dispatch.</p>
                            <p>NOT COVERED: We do not cover the cost associated with locating or gaining access to the septic tank or sewer hook-ups nor do we cover the cost of installing cleanouts or hook ups if they do not already exist; disposal of waste; chemical treatments of the septic tank or sewer lines; leach beds; leach lines; lateral lines; tanks; cesspools; mechanical pumps and/or systems. We will pay no more than $200 per contract term for access, diagnosis, repair; and pumping. </p>
                            <p>H.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Second Refrigerator</p>
                            <p>COVERED: All components and parts, including integral freezer unit, except: </p>
                            <p>NOT COVERED: Racks; shelves; glass; lighting; handles; doors, door seals, hinges, and gaskets; Freon; disposal and recapture of Freon; ice makers, ice crushers, beverage dispensers and their respective equipment; water lines and valve to ice maker; line restrictions; leaks of any kind; maintenance; interior thermal shells; freezers which are not an integral part of the refrigerator; wine chillers or mini refrigerators; food spoilage; noise without a related mechanical failure; multi-media centers and internet connection components.</p>
                            <p>I.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Stand Alone Freezer</p>
                            <p>COVERED: All components and parts, except:</p>
                            <p>NOT COVERED: Racks; shelves; glass; lighting; handles; doors, door seals, hinges, and gaskets; Freon; disposal and recapture of Freon; ice makers, ice crushers; water lines and valve to ice maker; line restrictions; leaks of any kind; maintenance; interior thermal shells; food spoilage; noise without a related mechanical failure; multi-media centers and internet connection components.</p>
                            <p>J.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Water Softener</p>
                            <p>COVERED: Mechanical parts and components of basic single water softener unit, including central head assembly; multi-level/twin softeners; piping to and from unit(s) and system tanks.</p>
                            <p>NOT COVERED: Any and all treatment, purification, odor control, iron filtration components and systems; discharge drywells; inadequate pressure; failure due to excessive water pressure or freeze damage; failures due to mineral and/or sediment; resin bed replacement and salt; leased or rented units; softening agents. We will pay no more than $500 per contract term for access, diagnosis, repair and/or replacement.</p>
                            <p>K.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Refrigerator Ice Maker</p>
                            <p>COVERED: Mechanical components and parts related to the kitchen refrigerator ice maker only, except:</p>
                            <p>NOT COVERED: Free standing ice makers; Freon; disposal and recapture of Freon; dispensers; ice crushers; water lines and valve to ice maker; line restrictions.&nbsp;<span class="tc2">We will pay no more than $200 per contract term for access, diagnosis, repair and/or replacement.</span></p>
                            <p>L.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Free Standing Ice Maker</p>
                            <p>COVERED: All mechanical components and parts, except:</p>
                            <p>NOT COVERED: Racks; shelves; glass; lighting; handles; doors, door seals, hinges, and gaskets; Freon; disposal and recapture of Freon, ice crushers; water lines and valve to ice maker; line restrictions; leaks of any kind; maintenance; interior thermal shells; noise without a related mechanical failure; leveling and balancing; commercial units.</p>
                            <p>M.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; GREENguard&trade; </p>
                            <p>COVERED: If a covered system or appliance (limited to Clothes Washer, Clothes Dryer, Refrigerator, and Dishwasher) fails per section I above and subject to all other Agreement inclusions, exclusions and limitations, and it cannot be repaired, we will replace the appliance with an ENERGY STAR qualified product (subject to availability, exclusions and limitations), one with similar and like features as existing appliance, except:</p>
                            <p>NOT COVERED: All other Agreement limitations of liability and exclusions apply.</p>
                            <p class="tc">N.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Lawn Sprinkler System</p>
                            <p class="tc">Note: Coverage is for lawn sprinkler systems only.</p>
                            <p class="tc">COVERED: Timers; valves; stoppages, except:</p>
                            <p class="tc">NOT COVERED: Hydraulic systems; malfunctioning due to lack of water pressure; digging of sprinkler lines; water lines; leak detections; batteries; drip irrigation systems; damage due to freezing, pets, cars, or lawn care equipment; sprinkler heads; seasonal maintenance; improper electrical current; systems using water containing corrosive chemicals, electrolytes, sand, dirt, silt, rust or agents that otherwise attack and degrade plastics.&nbsp;<span class="tc2">We will pay no more than $200 per contract term for access, diagnosis, repair and/or replacement.</span></p>
                            <p><strong>VII.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; GENERAL LIMITATIONS OF LIABILITY</strong></p>
                            <p>A.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The following are not included during the contract term; (i) malfunction or improper operation due to rust or corrosion of all systems and appliances, (ii) collapsed ductwork, (iii) known or unknown pre-existing conditions, deficiencies and/or defects.</p>
                            <p>B.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We are not responsible for the repair of any cosmetic defects or performance of routine maintenance.</p>
                            <p>C.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; At times it is necessary to open walls or ceilings to make repairs. The Service Contractor provided by us will close the opening, and return to a rough finish condition. We are not responsible for restoration of any wall coverings, floor coverings, plaster, cabinets, counter tops, tiling, paint, or the like. Rough finish is defined to include hanging of drywall, patching of drywall, stucco, and lath. Repair to rough finish does not include supplies or labor for paint, sanding, wall texture, wallpaper and/or tile work.&nbsp;<span class="tc2">We are not responsible for drywall or rough finish repairs on not covered claims</span>.</p>
                            <p>D.&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; This Agreement covers only repairs and/or replacements due to mechanical failure attributable to ordinary wear and tear. Accordingly, the Agreement does not cover failures which may result from other causes, such as without limitation abuse; misuse and/or neglect; lack of maintenance; rust and/or corrosion; noise without a related mechanical failure; chemical or sedimentary build up; failures due to calcium build-up; lightning strikes; missing parts; animal, pet and/or pest damage; power failure; power surge; fire; casualty; water damage; acts of God; structural and/or property damage; flood; smoke; earthquake; freeze damage; accidents; war; acts of terrorism; nuclear explosion, reaction, radiation or radioactive contamination; insurrection; riots; vandalism; or intentional destruction of property. This Agreement does not cover mechanical failures resulting directly or indirectly from or caused by mold, mildew, mycotoxins, fungus, bacteria, virus, condensation, and/or wet or dry rot regardless of the source, origin, or location and any other cause or event contributing concurrently or in any sequence to the mechanical failure. We are not responsible for drywall or rough finish repairs on not covered claims.</p>
                            <p>E.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This Agreement shall not cover any item(s) if they are mismatched systems with components having incompatible capacity ratings; modified from the original manufacturer design or application; items determined to be defective by the Consumer Product Safety Commission or the manufacturer and for which either has issued, or issues, a warning or recall, or which is otherwise necessitated due to failure caused by the manufacturer&rsquo;s improper design, use of improper materials and/or formulas, manufacturing process or any other manufacturing defect; improperly installed; or below the slab or basement floor of the home; or located outside the perimeter of the main foundation (i.e., outside the outer load bearing walls of the structure with the exception of central air conditioning unit, main electrical panel) or unless specifically covered with Optional Coverage purchased for items outside the main perimeter.</p>
                            <p>F.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This Agreement does not cover upgrading or making modifications to items due to, but not limited to, the following reasons: capacity (over or undersized); dimensional or design change; conditions of insufficient or excessive water pressure; conditions of inadequate wiring capacity; circuit overload; power failure and/or surge; failure to meet building code(s); zoning requirements; utility regulations; or failure to comply with local, state or federal laws or regulations.</p>
                            <p>G.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This Agreement does not cover any costs associated with construction, carpentry, or other modifications made necessary by the repair or replacement of existing equipment or installing different equipment. This Agreement does not cover any costs associated with any upgrades or modifications to comply with federal, state, and/or local law, code, regulation, or ordinance. All such costs are your responsibility.</p>
                            <p>H.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; SEER (Seasonal Energy Efficiency Ratio) operational compatibility: If we elect to replace an air conditioning condenser or heat pump unit, and it becomes necessary to make a mechanical modification to the evaporator coil in order to provide operational compatibility, we agree to pay the covered costs for one (1) of the following, determination is at our sole discretion, only: expansion metering device, or coil, or air handler. This Agreement does not cover any costs associated with modifications or upgrades required to match efficiency value, rating or ratio. </p>
                            <p>I.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This Agreement does not cover fees associated with the removal and/or disposal of old systems, appliances and components; any fees or costs associated with Freon reclamation.</p>
                            <p>J.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This Agreement does not cover fees associated with the removal and/or disposal of hazardous or toxic material or asbestos.</p>
                            <p>K.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This Agreement does not cover repair or replacement of systems, appliances or components classified by the manufacturer as commercial-grade.</p>
                            <p>L.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This Agreement does not cover (i) fees associated with use of cranes or other lifting equipment required to service any item or system; or (ii) excavation or other charges associated with gaining access to the well pump; or (iii) electronic computerized energy management systems or devices, or lighting and/or appliance management systems; or (iv) solar systems and solar components.&nbsp; </p>
                            <p>M.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This Agreement does not cover ductwork with the sole exception of ductwork that is exposed and readily accessible to service a mechanical failure of a covered air conditioning or heating system or item. This Agreement does not cover: asbestos insulated ductwork; concrete encased or inaccessible ductwork; crushed/collapsed ductwork; ductwork damaged by moisture, water, pests and/or animals; insulation; registers, grills and dampers; underground ductwork. Inaccessible ductwork refers to ductwork that is used in central heating and/or air conditioning systems that is not exposed and cannot readily be accessed for replacement or repair due to design and installation obstacles such as, but not limited to, permanent partitions, chimneys, etc., and ductwork embedded in floors, walls or ceilings.</p>
                            <p>N.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This Agreement does not cover any costs incurred to gain and/or close access to a covered item, system, appliance or component in situations where there is not adequate capacity or space for serviceability caused by, but not limited to, walls, floors, ceilings, toilets, sinks, permanently installed fixtures, cabinets, snow/ice covered areas, flooded areas, or personal property. In the event it is necessary to open walls, floors, or ceilings, or to move such fixtures, cabinets, or personal property to perform a diagnosis or service, we are not responsible for restoring such openings, items, or property. This Agreement does not cover any costs associated with equipment to gain access or permit serviceability such as but not limited to scaffolding.</p>
                            <p>O.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This Agreement does not cover delays or failures to provide service caused by, or related to any of the exclusions listed herein; shortages of labor and/or materials; or any other cause beyond our reasonable control. This Agreement does not cover additional charges to access or transport materials, supplies, or independent Service Contractors to the covered property due to lack of or inhibited serviceability, such as but not limited to, tolls, required use of ferries or barges and/or remote locations.</p>
                            <p>P.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This Agreement does not cover any incidental, consequential, special, and/or punitive damages, and you agree to waive any and all claims for such damages, arising from, resulting from and/or related to the failure of any item or system, including, but not limited to, food spoilage, loss of income, additional living expenses, and/or any loss, damage, cost or expense directly or indirectly arising out of or resulting from, or in any manner related to mold, mildew, mycotoxins, fungus, bacteria, viruses, condensation, wet or dry rot and/or other property damage.</p>
                            <p>Q.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This Agreement does not cover repairs or replacements of any item covered by other insurance, warranties or guarantees, including but not limited to, manufacturer&rsquo;s, contractor&rsquo;s, builder&rsquo;s, distributor&rsquo;s, or home warranty. Our Coverage is secondary to such insurance, warranties, or guarantees.</p>
                            <p>R.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This Agreement does not cover any mechanical failure when the covered item or system has been repaired, modified, disabled or adjusted in any way which prevents us or our independent Service Contractor(s) from inspecting, diagnosing and/or repairing the mechanical failure. This Agreement does not cover any mechanical failure to any covered item or system that has been improperly altered, repaired, installed, modified or damaged in the course of remodeling or unauthorized repair.</p>
                            <p>S.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This Agreement does not cover performance of routine maintenance. You are responsible for performing all routine maintenance and cleaning for all covered items and systems as specified and recommended by the manufacturer. For example, you are responsible for providing maintenance and cleaning pursuant to manufacturers&rsquo; specifications, such as periodic cleaning of heating and air conditioning systems, evaporator coils and condenser coils, as well as periodic filter replacement. We will not pay for repairs or failures that result from your failure to perform normal or routine maintenance. </p>
                            <p>T.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We are not liable for any damages that result from a Service Contractor&rsquo;s service, delay in providing service or failure to provide service. We are not liable for any incidental, consequential, special, and/or punitive damages, whether caused by negligence or any other cause, and you agree to waive any and all claims for such damages, arising from, resulting from or related to any Service Contractor&rsquo;s service, delay in providing service or failure to provide service, including, but not limited to, damages, resulting from delays in securing parts and/or labor, the failure of any equipment used by an independent Service Contractor, labor difficulties, and/or the negligent, tortuous and/or unlawful acts or omissions of any independent Service Contractor.</p>
                            <p>U.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We have the sole right to determine whether a covered system or appliance will be repaired or replaced. We are responsible for installing replacement equipment of similar features, capacity, and efficiency, but not for matching dimensions, brand or color. We are not responsible for upgrades, components, parts, or equipment required due to the incompatibility of the existing equipment with the replacement system or appliance or component or part thereof or with new type of chemical or material utilized to run the replacement equipment including, but not limited to, differences in technology, refrigerant requirements, or efficiency as mandated by federal, state, or local governments. If parts are no longer available, we will offer a cash payment in the amount of the average cost between parts and labor of the covered repair. We reserve the right to locate parts at any time.&nbsp; We are not liable for replacement of entire systems or appliances due to obsolete, discontinued or unavailability of one or more integral parts. However, we will provide reimbursement for the costs of those parts determined by reasonable allowance for the fair value of like parts. We reserve the right to rebuild a part or component, or replace with a rebuilt part or component.</p>
                            <p>V.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>We reserve the right to offer cash back in lieu of repair or replacement in the amount of our actual cost, which at times may be less than retail, to repair or replace any covered system, component or appliance. In the event a covered system or appliance is deemed irreparable or it is not cost effective to repair, we may replace the system or appliance with a system or appliance of like capacity, the price of which shall not exceed the depreciated value of the system or appliance being replaced. RHW is not responsible for installation. The cash settlement shall be in an amount not to exceed the depreciated value of the component, system, or appliance being replaced. In the event you elect to use the cash back funds to repair rather than replace your system or appliance, said system or appliance will no longer be covered by RHW.</strong></p>
                            <p>W.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We are not liable for the repair or replacement of commercial grade equipment, systems or appliances. We shall pay no more than $1,000 in aggregate for professional series or like appliances such as, but not limited to, brand names such as Sub Zero, Viking, Wolf, Bosch, Jenn-Air, GE Monogram, Thermador, Miele, Fisher &amp; Paykel, and etc.</p>
                            <p>X.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; You agree that we are not liable for the negligence or other conduct of the Service Contractor, nor are we an insurer of Service Contractor&rsquo;s performance. You also agree that we are not liable for consequential, incidental, indirect, secondary, or punitive damages. You expressly waive the right to all such damages. Your sole remedy under this Agreement is recovery of the cost of the required repair or replacement, whichever is less. You agree that, in no event, will our liability exceed $1500 per contract item for access, diagnosis, repair and/or replacement.</p>
                            <p>Y.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In the event you threaten to harm or actually harm the safety or well-being of: (i) RHW ; (ii) any employee of RHW ; (iii) a Service Contractor; or (iv) any property of RHW or the Service Contractor, you will be in breach of this Agreement. In the event you breach this or any other obligation under this Agreement, RHW may refuse to provide service to you and may cancel this Agreement.</p>
                            <p><strong>VIII.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MULTIPLE UNITS AND INVESTMENT PROPERTIES</strong></p>
                            <p>A.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If the Agreement is for 2-family, 3-family, or 4-family dwelling, then every unit within such dwelling must be covered by the Agreement with applicable Optional Coverage for Coverage to apply to shared systems and appliances.</p>
                            <p>B.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If this Agreement is for a unit within a multiple unit of five (5) or more, then only items contained within the confines of each individual unit are covered. Shared systems and appliances are excluded.</p>
                            <p>C.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Except as otherwise provided in this section, shared systems and appliances are excluded.</p>
                            <p><strong>IX.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MEDIATION </strong></p>
                            <p>In the event of a dispute over claims or Coverage you agree to file a written informal claim with us and allow us twenty (20) calendar days to respond to the claim. The parties agree to mediate in good faith before resorting to mandatory arbitration. All written claims should be mailed to Regal Home Warranty, Mediation Department, 300 McGaw Drive, 2nd Floor, Edison, NJ 08837, or e-mailed to Mediation@regalhomewarrantyn.com .</p>
                            <p>Except where prohibited, if a dispute arises from or relates to this Agreement or its breach, and if the dispute cannot be settled through direct discussions you agree that:</p>
                            <p>A.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Any and all disputes, claims and causes of action arising out of or connected with this Agreement shall be resolved individually, without resort to any form of class action, and exclusively by the American Arbitration Association under its Commercial Mediation Rules. Controversies or claims shall be submitted to arbitration regardless of the theory under which they arise, including without limitation contract, tort, common law, statutory, or regulatory duties or liability.</p>
                            <p>B.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Any and all claims, judgments and awards shall be limited to actual out-of-pocket costs incurred to a maximum of $1500 per claim, but in no event attorneys' fees.</p>
                            <p>C.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Under no circumstances will you be permitted to obtain awards for, and you hereby waive all rights to claim, indirect, punitive, incidental and consequential damages and any other damages, other than for actual out-of-pocket expenses, and any and all rights to have damages multiplied or otherwise increased. All issues and questions concerning the construction, validity, interpretation and enforceability of this Agreement, shall be governed by, and construed in accordance with, the laws of the State of New Jersey, U.S.A. without giving effect to any choice of law or conflict of law rules (whether of the State of New Jersey or any other jurisdiction), which would cause the application of the laws of any jurisdiction other than the State of New Jersey.</p>
                            <p>D.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Any claim must be brought in the parties&rsquo; individual capacity, and not as a plaintiff or class member in any purported class, collective, representative, multiple plaintiff, or similar proceeding (&ldquo;Class Action&rdquo;). The parties expressly waive any ability to maintain any Class Action in any forum. The arbitrator shall not have authority to combine or aggregate similar claims or conduct any Class Action nor make an award to any person or entity not a party to the arbitration. Any claim that all or part of this Class Action Waiver is unenforceable, unconscionable, void, or voidable may be determined only by a court of competent jurisdiction and not by an arbitrator. THE PARTIES UNDERSTAND THAT THEY WOULD HAVE HAD A RIGHT TO LITIGATE THROUGH A COURT, TO HAVE A JUDGE OR JURY DECIDE THEIR CASE AND TO BE PARTY TO A CLASS OR REPRESENTATIVE ACTION, HOWEVER, THEY UNDERSTAND AND CHOOSE TO HAVE ANY CLAIMS DECIDED INDIVIDUALLY, THROUGH ARBITRATION.</p>
                            <p><strong>X.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; SEVERABILITY</strong></p>
                            <p>If any provision of this Agreement is found to be contrary to law by a court of competent jurisdiction, such provision shall be of no force or effect; but the remainder of this Agreement shall continue in full force and effect.</p>
                            <p><strong>XI.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; RENEWALS AND TRANSFER OF AGREEMENT</strong></p>
                            <p>A.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; RHW may, in its sole discretion, elect to renew this Agreement for a one year contract term, unless otherwise approved by RHW. In the event we elect to renew your Agreement, you will be notified of the terms within sixty (60) days prior to expiration of your Agreement. Unless you notify RHW prior to expiration of your Agreement, your Agreement will be automatically renewed and you will be charged applicable plan fees.</p>
                            <p>B.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If you select the monthly payment option and we elect to renew your Agreement, we will notify you of applicable rate and terms of renewal during the tenth month of your Agreement. You will automatically be renewed for a monthly coverage period unless you notify us in writing thirty (30) days prior to the expiration of the Agreement. Your first payment for the next contract term will be construed as authorization for month-to-month charges.</p>
                            <p>C.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If your covered property is sold during the term of this Agreement, you must notify us of the change in ownership and submit the name of the new owner by phoning 1-860-777-0204 in order to transfer Agreement to the new owner.</p>
                            <p>D.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; You may transfer this Agreement at any time.&nbsp; There is no fee to transfer the Agreement.</p>
                            <p><strong>XII.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; CANCELLATION</strong></p>
                            <p>A.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This Agreement may be cancelled by RHW for the following reasons: (i) nonpayment of Agreement fees or other breach of this Agreement by the customer; (ii) nonpayment of Trade Service Call Fee, as stated in section IV; (iii) fraud or misrepresentation by the customer and/or customer representative of facts material to RHW&rsquo;s issuance of this Agreement; or (iv) a change in laws or regulations that has a material effect on the business of RHW or RHW&rsquo;s ability to fulfill its obligations under this Agreement.</p>
                            <p>B.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; You may cancel this Agreement within the first thirty (30) days of the order date for a full refund of the paid contract fees, less any service costs incurred by us.</p>
                            <p>C.&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mutual agreement of us and you. If this Agreement is canceled after thirty (30) days, you shall be entitled to a pro rata refund at the standard contract fee rate for the unexpired term, less a $50 administrative fee and any service costs incurred by us. If we have provided services and the amount of the service costs incurred by us is greater than the contract fees paid, then no refund will be due to you. All cancellation requests must be submitted in writing.</p>
                        </div>



                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<?php $this->load->view('common/footer'); ?>
